### ISSUE TITLE
Doesn't build

### ISSUE THREAD

**Issue by ghost** [littlebunch/bfpd-sql#1]
I'm unfamiliar with Go, so this might just me doing it wrong, but when I follow the instructions I get:

jeroen@jeroen-ThinkPad-P50:~/www/bfpd-sql$ go build -o bfpdloader main.go
main.go:14:2: cannot find package "github.com/littlebunch/bfpd-sql/config" in any of:
	/usr/lib/go-1.13/src/github.com/littlebunch/bfpd-sql/config (from $GOROOT)
	/home/jeroen/go/src/github.com/littlebunch/bfpd-sql/config (from $GOPATH)
main.go:15:2: cannot find package "github.com/littlebunch/bfpd-sql/ds/mariadb" in any of:
	/usr/lib/go-1.13/src/github.com/littlebunch/bfpd-sql/ds/mariadb (from $GOROOT)
	/home/jeroen/go/src/github.com/littlebunch/bfpd-sql/ds/mariadb (from $GOPATH)
main.go:16:2: cannot find package "github.com/littlebunch/bfpd-sql/ingest" in any of:
	/usr/lib/go-1.13/src/github.com/littlebunch/bfpd-sql/ingest (from $GOROOT)
	/home/jeroen/go/src/github.com/littlebunch/bfpd-sql/ingest (from $GOPATH)
main.go:17:2: cannot find package "github.com/littlebunch/bfpd-sql/ingest/branded" in any of:
	/usr/lib/go-1.13/src/github.com/littlebunch/bfpd-sql/ingest/branded (from $GOROOT)
	/home/jeroen/go/src/github.com/littlebunch/bfpd-sql/ingest/branded (from $GOPATH)
main.go:18:2: cannot find package "github.com/littlebunch/bfpd-sql/ingest/dictionaries" in any of:
	/usr/lib/go-1.13/src/github.com/littlebunch/bfpd-sql/ingest/dictionaries (from $GOROOT)
	/home/jeroen/go/src/github.com/littlebunch/bfpd-sql/ingest/dictionaries (from $GOPATH)
main.go:19:2: cannot find package "github.com/littlebunch/bfpd-sql/model" in any of:
	/usr/lib/go-1.13/src/github.com/littlebunch/bfpd-sql/model (from $GOROOT)
	/home/jeroen/go/src/github.com/littlebunch/bfpd-sql/model (from $GOPATH)

**Comment by littlebunch** [comment]
Sorry, didn't commit go.mod.  You can do a pull and it should build now.  Note, however, that you will not be able to load the latest csv from the USDA site with this package since the csv spec has changed .  And, I will probably not be updating this package as I'm no longer working in Go having moved on to Rust.  

 So, you might want to have a look at [bpfd-rs](https://github.com/littlebunch/bfpd-rs) which will work with the April 2021 release.   I will be uploading the Oct 2021 release soon.  Plus, you get a choice of database -- mariadb or postgresql.

**Comment by ghost** [comment]
Cool, thanks!
